### ISSUE TITLE
使用书签并没有出发关键字

### ISSUE THREAD

**Issue by aixiaodeshisan** [tintinweb/vscode-inline-bookmarks#1]
![image](https://user-images.githubusercontent.com/43919501/71554410-892b6580-2a59-11ea-8453-905c24fbcdba.png)

**Comment by tintinweb** [comment]
Hi @aixiaodeshisan,

can you confirm that the highlighting works when adding a space after `@follow-up`? The default pattern requires a [tab, space or line-break](https://github.com/tintinweb/vscode-inline-bookmarks/blob/c9dfbe19a4959e3e17f9878254e9014eb7606c22/package.json#L98) after the bookmark label.
