### ISSUE TITLE
Just installed, inline bookmarking using default keywords not creating bookmark

### ISSUE THREAD

**Issue by offroadkev** [tintinweb/vscode-inline-bookmarks#10]
I see the 'Inline Bookmarks' panel in my sidebar, but nothing happens when I try to type `@todo`, `@audit`, `@note`, etc. inside the comment.

For example in my typescript file I tried

```javascript
// @todo
// @audit
```

Also, when go into the 'Inline Bookmarks' sidebar panel and try to toggle the 'refresh' or the 'show bookmarks for visible/all files' I get errors

`command 'inlineBookmarks.toggleShowVisibleFilesOnly' not found`

and

`command 'inlineBookmarks.refresh' not found`

**Comment by offroadkev** [comment]
fwiw, I already uninstalled, closed visual studio code and then re-opened VSC and reinstalled, closed it again and reopened it...still isn't working for me.

Thanks in advance for your assistance.  I'm excited about this plugin.

**Comment by tintinweb** [comment]
Hi @vegaskev,

thanks for the report!
Can you toggle the developer tools (cmd + shift + p on mac, toggle developer tools), goto console and check if you see an exception there and/or provide the output you see?

thanks,
tin

**Comment by offroadkev** [comment]
Sure thing @tintinweb , here you go

```
workbench.desktop.main.js:sourcemap:2646 Error: command 'inlineBookmarks.refresh' not found
    at u._tryExecuteCommand (workbench.desktop.main.js:sourcemap:3222)
    at workbench.desktop.main.js:sourcemap:3222
    at processTicksAndRejections (internal/process/task_queues.js:89)
    at async o.run (workbench.desktop.main.js:sourcemap:141)
onDidNotificationChange @ workbench.desktop.main.js:sourcemap:2646
workbench.desktop.main.js:sourcemap:2646 Error: command 'inlineBookmarks.toggleShowVisibleFilesOnly' not found
    at u._tryExecuteCommand (workbench.desktop.main.js:sourcemap:3222)
    at workbench.desktop.main.js:sourcemap:3222
    at processTicksAndRejections (internal/process/task_queues.js:89)
    at async o.run (workbench.desktop.main.js:sourcemap:141)
onDidNotificationChange @ workbench.desktop.main.js:sourcemap:2646
workbench.desktop.main.js:sourcemap:2646 Error: command 'inlineBookmarks.toggleShowVisibleFilesOnly' not found
    at u._tryExecuteCommand (workbench.desktop.main.js:sourcemap:3222)
    at workbench.desktop.main.js:sourcemap:3222
    at async o.run (workbench.desktop.main.js:sourcemap:141)
onDidNotificationChange @ workbench.desktop.main.js:sourcemap:2646
workbench.desktop.main.js:sourcemap:2646 Error: command 'inlineBookmarks.refresh' not found
    at u._tryExecuteCommand (workbench.desktop.main.js:sourcemap:3222)
    at workbench.desktop.main.js:sourcemap:3222
    at async o.run (workbench.desktop.main.js:sourcemap:141)
```

**Comment by offroadkev** [comment]
...interesting.  Everything seems to be working fine now.

**Comment by tintinweb** [comment]
thanks for the feedback @vegaskev! It is definitely an activation issue. I am not sure what is causing it tbh. The extension is registered to be activated for all activation events (all languages, files, ..) and in addition to that we also register the commands themselves to make sure the extension is loaded when one of the commands is called. Something in that process seems not to be working right.

Let me know if this happens again. Maybe there was an exception/error that prevented the extension from loading.

**Comment by rholland** [comment]
working on windows 10:

Bookmarks are not found and I am getting the error

`command "inlineBookmarks.refresh" not found`

when I click the refresh icon

and

`command 'inlineBookmarks.toggleShowVisibleFilesOnly' not found`

when I click the show bookmarks icon

here are some errors from console debugger:

`notificationsAlerts.ts:38 Error: command 'inlineBookmarks.toggleShowVisibleFilesOnly' not found
    at u._tryExecuteCommand (commandService.ts:80)
    at commandService.ts:73
    at async o.run (actions.ts:190)
onDidNotificationChange @ notificationsAlerts.ts:38
(anonymous) @ notificationsAlerts.ts:26
fire @ event.ts:581
addNotification @ notifications.ts:171
error @ notificationService.ts:57
(anonymous) @ compositePart.ts:259
fire @ event.ts:581
run @ actions.ts:193
async function (async)
run @ actions.ts:190
onClick @ menuEntryActionViewItem.ts:292
(anonymous) @ actionbar.ts:150
processImmediate @ internal/timers.js:439
notificationsAlerts.ts:38 Error: command 'inlineBookmarks.refresh' not found
    at u._tryExecuteCommand (commandService.ts:80)
    at commandService.ts:73
    at async o.run (actions.ts:190)`

**Comment by rholland** [comment]
I played around a little bit.  It seems like the errors above get thrown if the default trigger words are changed or deleted in certain ways.  Also I noticed that if I set the trigger words to a color - say green, the bookmark icon takes on that color but the words themselves remain reddish, irrespective of the bookmark icon color [note: I found I can override it in the custom json settings].

Also it is not really clear where the default trigger words are stored.  If I uninstall and reinstall the extension any changes to defaults seem to persist.  It seems as if they are retained somewhere in the program after uninstall and then rewritten to the json settings on reinstall?   Are you saving settings somewhere other than the user and workspace json?

It seems as if the errors may be related to the way the default settings are handled.

Thanks for the great program!

**Comment by tintinweb** [comment]
Hi @rholland,

> I played around a little bit. It seems like the errors above get thrown if the default trigger words are changed or deleted in certain ways.

I'll look into that. Changing words may require a vscode reload and a refresh of the view.

> Also I noticed that if I set the trigger words to a color - say green, the bookmark icon takes on that color but the words themselves remain reddish, irrespective of the bookmark icon color [note: I found I can override it in the custom JSON settings].

By default (unless you specify some custom decorations) the extension is not changing the colors of the words. What you see is very likely an artifact of another extension (e.g git) or vscode itself coloring files. I believe that the git extensions change filename colors to red if the file was modified, green if it is untracked, theme color if unchanged. We're just taking on the same decoration for filenames in that view that you would see in the explorer view.

> Also it is not really clear where the default trigger words are stored. If I uninstall and reinstall the extension any changes to defaults seem to persist. It seems as if they are retained somewhere in the program after uninstall and then rewritten to the JSON settings on reinstall? Are you saving settings somewhere other than the user and workspace JSON?

there are hardcoded defaults in the extension and they are merged with whatever you configure in the extension settings. Extension settings are not reset if you uninstall the extension. go to `vscode -> settings: inline-bookmarks` and hit the gear icon to reset that setting. Note that blue bar to the left of the setting is indicating that it has been changed.

![image](https://user-images.githubusercontent.com/2865694/73834533-2f624c00-480c-11ea-807d-e71f0416f4bf.png)

> It seems as if the errors may be related to the way the default settings are handled.

if you filter the log for all "warning, error" messages do you see any other exceptions that might be related? The "command failed" error indicates that the extension was unable to load. if that's the case there might be some traces way earlier in the log.

> Thanks for the great program!

thanks for the feedback, happy you like it 🙌

**Comment by rholland** [comment]
Appreciate the thorough response. Everything seems stable now, and it is doing what I need, but I will let you know if anything else crops up.

**Comment by offroadkev** [comment]
@tintinweb fwiw I haven't had the issue since my last comment 8 days ago.  I appreciate you looking into it.  I have a feeling it was activation related.  Closing issue.  Thanks for the great VSC plugin.

**Comment by tintinweb** [comment]
I was able to reproduce it one time on my spare machine starting a new project. A reload fixed it. Not yet sure what is happening but it does not seem to be persistent 🤔
