### ISSUE TITLE
Simplify finding bookmarks

### ISSUE THREAD

**Issue by maurelian** [tintinweb/vscode-inline-bookmarks#11]
I have about 25 bookmarks in one file right now for an audit I'm working on. I want to be able to search through them easily to find the one I'm looking for. 

The sidebar view only shows the first few words. 
I think the right solution is a command like `inlineBookmarks: list comments`, which would bring up a filterable list much like the built in `Go To File...` command.

**Comment by tintinweb** [comment]
@maurelian, please give it a try: [vscode-inline-bookmarks-0 0 17-feat-quickpick vsix](https://user-images.githubusercontent.com/2865694/81101026-c32bdd00-8f0d-11ea-8745-95956a2d2c90.png) --> rename to .vsix

![image](https://user-images.githubusercontent.com/2865694/81101073-da6aca80-8f0d-11ea-800b-3d200366cd46.png)

cmd + shift + p -> select bookmark
