### ISSUE TITLE
Add a command to jump to the next bookmark

### ISSUE THREAD

**Issue by maurelian** [tintinweb/vscode-inline-bookmarks#12]
I would like to be able to quickly move through the bookmarks in a file in the order they occur. 
There should be a command for going to the next one, and the previous one.

**Comment by tintinweb** [comment]
@maurelian here's a quick shot on this. only works for the current file. commands:`inlineBookmarks.jumpToNext` `inlineBookmarks.jumpToPrevious`

see uploaded extension in https://github.com/tintinweb/vscode-inline-bookmarks/issues/14#issuecomment-585166568

**Comment by maurelian** [comment]
This works great, thank you!
