### ISSUE TITLE
Make the explorer list filterable by tag

### ISSUE THREAD

**Issue by maurelian** [tintinweb/vscode-inline-bookmarks#14]
I'd like to be able to filter these so I can focus on one at a time, ie. only `@audit`, and ignore everything marked `@audit-ok`. 

![image](https://user-images.githubusercontent.com/23033765/73884372-bc6ccb80-4833-11ea-8963-056512b06219.png)

**Comment by tintinweb** [comment]
@maurelian give it a try: `inlineBookmarks.setTreeViewFilterWords`

takes a list of space or semicolon-delimited list of regexes. filters on treeview label. also affects jumpToNext, jumpToPrevious

![image](https://user-images.githubusercontent.com/2865694/74332069-4ddcc000-4d95-11ea-89b2-ae41f5307662.png)


[vscode-inline-bookmarks-0 0 16 vsix](https://user-images.githubusercontent.com/2865694/74331788-b4151300-4d94-11ea-8be1-cf956cf5914b.png) (rename png->vsix)

**Comment by maurelian** [comment]
This also works great!
