### ISSUE TITLE
go to previous or next bookmark

### ISSUE THREAD

**Issue by rholland** [tintinweb/vscode-inline-bookmarks#15]
It would be helpful to have a shortcut key to go the next or previous bookmark.  Thanks for great program.

**Comment by tintinweb** [comment]
this is likely a dup of #12. Feel free to test-pilot the release candidate mentioned in the issue. Once this is released you should be able to assign a keyboard shortcut to the new commands in `code -> preferences -> keyboard shortcuts`.
