### ISSUE TITLE
Only show bookmarks for file that is currently in focus

### ISSUE THREAD

**Issue by mindfulJS** [tintinweb/vscode-inline-bookmarks#2]
Please can you add the option to show bookmarks only for the file that is currently open and in focus (a la VScode's outline)?
The reason is there can be too many files in the inline bookmarks panel and navigating between them all is cumbersome.

**Comment by tintinweb** [comment]
@mindfulJS sounds like a good idea. I'll add a button to toggle all vs. current file bookmarks.
