### ISSUE TITLE
Cannot ignore .d.ts extension

### ISSUE THREAD

**Issue by SamHasler** [tintinweb/vscode-inline-bookmarks#21]
I've set the list of ignored extensions to `.d.ts` but I'm still seeing them in the panel list after clicking on the refresh button.

**Comment by tintinweb** [comment]
Hey @SamHasler,

this sounds like a bug. looks like this setting may not have an effect on the treeview 🤔 Do you see any decorations in that file?

did you first add a bookmark to a file and then added it to the ignore list?

**Comment by SamHasler** [comment]
It had already remembered seeing several @deprecated comments in .d.ts files that I had opened whilst debugging but hadn't written myself. I then added .d.ts to the ignored extensions expecting it to then filter out those file.

**Comment by tintinweb** [comment]
this feature is not really meant to filter the view but to completely exclude file-extensions from being processed. however, it can also be used in that way. I've fixed your specific issue with #30aac5 clearing bookmarks for existing files if we find out the extension is to be ignored.

**Comment by SamHasler** [comment]
Thank you! I think this will be less confusing for people trying to filter out files after they've already been remembered.
