### ISSUE TITLE
suggestion: render the comment same color with the bookmark tag 

### ISSUE THREAD

**Issue by zhangaz1** [tintinweb/vscode-inline-bookmarks#23]
effect like "Better Comments" 
https://marketplace.visualstudio.com/items?itemName=aaron-bond.better-comments
https://github.com/aaron-bond/better-comments/raw/master/images/better-comments.PNG

**Comment by SamHasler** [comment]
It can already do this, just add `.*` to the end of each trigger word. (You may need to close and reopen VS Code to see the config change. I think this extension only reads the config when initialising)

**Comment by tintinweb** [comment]
closing, thanks @SamHasler
