### ISSUE TITLE
Bug in the Set Filter View

### ISSUE THREAD

**Issue by AxelGauffre** [tintinweb/vscode-inline-bookmarks#24]
Hi tintinweb
Very good extension. Thank you!

I think I found a bug however, in the Set Filter View feature:

1. **In a** .js **document**, just **type the following to lines**:

```
//@note - aaa
//@note - bbb
```

2. Then, **launch Set Filter View**, and **type "note"** (without the quotes)

==> **Only @note - aaa appears** in the Explorer.

Am I missing something?

**Comment by tintinweb** [comment]
whoop, definitely a bug. should be fixed with the next release.

thanks for reporting @AxelGauffre 

cheers 🙌

**Comment by tintinweb** [comment]
published with v0.0.19.
