### ISSUE TITLE
The filter button doesn't work

### ISSUE THREAD

**Issue by oxk4r01** [tintinweb/vscode-inline-bookmarks#26]
It doesn't do anything. Bookmarks are permanently shown. No visibility toggle.

**Comment by tintinweb** [comment]
Hi @oxk4r01,

which filter functionality are you referring to?

* the "eye" like button in the bookmarks view
* or the `InlineBookmarks: Set View Filter` command?

**Comment by tintinweb** [comment]
closing, cannot reproduce.
