### ISSUE TITLE
Ignore bookmarks from git

### ISSUE THREAD

**Issue by kannan-balasubramanian** [tintinweb/vscode-inline-bookmarks#29]
Presently the bookmarks on the side pane lists the entries in the git files. If there is a setting to ignore git files, that would be great.

**Comment by tintinweb** [comment]
can you provide more information (screenshot)?

**Comment by tintinweb** [comment]
it's excluded from the workspace scanning.

https://github.com/tintinweb/vscode-inline-bookmarks/blob/2f776a5f8b4914b8f03cd734d3900a1f23dcc35f/package.json#L288-L302

please reopen if this is still an issue and provide detailed information.
