### ISSUE TITLE
bookmarks don't refresh after selecting a file (new bookmark toggle)

### ISSUE THREAD

**Issue by mindfulJS** [tintinweb/vscode-inline-bookmarks#3]
In current file view please can you make the bookmarks to automatically refresh after selecting a new file?
Also it would be great to have the tree expanded by default (in single file view only) to show the bookmarks for that single file.
Keep up the good work it is a brilliant tool.

**Comment by tintinweb** [comment]
Hey @mindfulJS,

changed it to show all bookmarks of visible editor windows (e.g. if you have 2 files open in split view you'll see both).

ad. 2nd request: I am thinking about adding a "keep expanded" button to the view.

changes are not yet published.
