### ISSUE TITLE
Could we please see an option to allow the icon color to get fetched from the text color?

### ISSUE THREAD

**Issue by ItsCubeTime** [tintinweb/vscode-inline-bookmarks#30]

**Comment by ItsCubeTime** [comment]
If it was to be implemented I would happily make and share custom styles for the following bookmarks (with there coresponding colors/shades):

![image](https://user-images.githubusercontent.com/20190653/106646149-a3554280-658d-11eb-81ef-3f01867a8d2c.png)

**Comment by tintinweb** [comment]
I think one problem I faced, in the beginning, was that gutter icons cannot be generated on demand (in memory). I'll check if anything changed with this and keep it as a feature request for now.

cheers.

**Comment by ItsCubeTime** [comment]
If it's to any use, there is another extension, "comment anchors" which has this feature. It's open source here on github as well.

Another thing I think would be neat is if the extension could automatically refresh itself when changes happen to the settings.json file. Or just a simple refresh button somewhere otherwise.

Great extension btw

**Comment by rkodey** [comment]
> If it's to any use, there is another extension, "comment anchors" which has this feature. It's open source here on github as well.
> Great extension btw

Thanks @ItsCubeTime for the tip!  I found a similar approach in GitLens that was fairly simple to add in.  Hopefully @tintinweb can merge my pull requests for you quickly!
