### ISSUE TITLE
"List Bookmarks" command should respect "Show Bookmarks for Visible Editors / All Files"

### ISSUE THREAD

**Issue by AlexanderArvidsson** [tintinweb/vscode-inline-bookmarks#32]
Currently, when specifying that bookmarks should only show for the current file, the list bookmarks command shows bookmarks for all files which can get messy if you have lots of bookmarks that are similar.

Can we make sure that the list command respects the setting, or get another setting that filters for only the visible editors?
My workflow is that I jump to files through vim bindings and then open a list, search and go to the bookmark. This is problematic when the list shows all files, since I have comments that are similar. It forces me to find the right file which takes time.

![image](https://user-images.githubusercontent.com/2972103/109015951-f23a5780-76b5-11eb-96be-36f9711b6b38.png)
![image](https://user-images.githubusercontent.com/2972103/109015961-f6667500-76b5-11eb-8444-823ed6ad6085.png)

Also, great extension, exactly what I have been looking for, and something that other bookmarks extensions are lacking (those extensions have bookmarks that are jumping around with git changes and even when editing locally sometimes because they are not inline).

**Comment by tintinweb** [comment]
Hey @AlexanderArvidsson,

are you talking about the "list" or "select bookmark" command?

**Comment by tintinweb** [comment]
I went ahead and implemented it for both "list" and "select". Please note that the "Show bookmarks for visible editors" setting only applies to the bookmarks treeview object.

cheers,
tin
