### ISSUE TITLE
Cannot read property '_uri' of undefined

### ISSUE THREAD

**Issue by mindfulJS** [tintinweb/vscode-inline-bookmarks#33]
Bookmarks for visible editors (individual files) do not show in the latest version of VS Code 1.54.1. Error message: "Cannot read property '_uri' of undefined".
But bookmarks for all files work fine.

**Comment by abdevts** [comment]
same here

**Comment by N-Gol** [comment]
Got the same error, found that the option of showing bookmarks from open editors only is not working.

To solve change "_documentData._uri" with "document.uri" at ".vscode\extensions\tintinweb.vscode-inline-bookmarks-VERSION\src\extension.js" on line 285
and change "_visibleRanges" to "visibleRanges" on line 287
and "_documentData._uri" with "document.uri" at ".vscode\extensions\tintinweb.vscode-inline-bookmarks-VERSION\src\features\inlineBookmarks.js" on line 421

**Comment by tintinweb** [comment]
Sorry for the late reply on this one. Seems like vscode removed access to the `_uri` attribs with the latest update. Will get this out with the 0.0.21 release later today.

thanks for the reports!
