### ISSUE TITLE
Overview ruler bookmark highlight

### ISSUE THREAD

**Issue by evegreen** [tintinweb/vscode-inline-bookmarks#35]
Hi @tintinweb ! Thanks for good useful extension)
It is possible to display bookmarks on overview ruler (editor scroll)?

**Comment by tintinweb** [comment]
Hi @evegreen,

looks like we only display the blue bookmark in the overview 😬. can you confirm? We can easily add the other bookmarks as well. Would it be too cluttered if we display all of them? Should we make this an optional feature or default?

https://github.com/tintinweb/vscode-inline-bookmarks/blob/master/src/features/inlineBookmarks.js#L311

**Comment by evegreen** [comment]
![Screenshot from 2021-05-07 16-55-51](https://user-images.githubusercontent.com/16580584/117432985-2b643300-af55-11eb-8506-99c5eda98c42.png)

"overviewRulerColor" for each `decoId` works well for me, thanks!
I'm not shure about this default settings without overviewRulerColor disable switcer )
