### ISSUE TITLE
Multiline string settings are now supported in the settings editor

### ISSUE THREAD

**Issue by rzhao271** [tintinweb/vscode-inline-bookmarks#36]
Ref microsoft/vscode#79571

Hi! Just a note that you can now add the `"editPresentation": "multilineText"` key-value pair to any string setting that can take multiple lines (such as `inline-bookmarks.default.words.red`). In the settings editor, the setting will then display a textarea rather than a single-line inputbox. The feature is currently available in the Insiders edition of VS Code, and will be released to Stable in around two weeks.

However, note that tab characters currently cannot be entered into the textarea. That issue is being tracked at https://github.com/microsoft/vscode/issues/129260. In the meantime, you may want to either use spaces for the setting, or convert the setting to a single-line setting that takes in regex instead, such as `\\t` instead of `\t` for tab.

**Comment by tintinweb** [comment]
Thanks for the heads-up @rzhao271 🙌  Not intending to change this to multiline but if that's the case I'll consider the new feature.

cheers,
tin
