### ISSUE TITLE
single file view does not seem to refresh automatically when selecting a file

### ISSUE THREAD

**Issue by mindfulJS** [tintinweb/vscode-inline-bookmarks#4]
It seems when several tabs are open (with vscode setting "workbench.editor.enablePreview": false) the single file view does not automatically refresh when selecting different files/tabs.

**Comment by tintinweb** [comment]
can you give me detailed steps to reproduce?

**Comment by mindfulJS** [comment]
- disable the setting "Workbench › Editor: Enable Preview" in vscode
- restart vscode
- open a file (-> no bookmarks showing)
**- [click on rescan workspace button]**
**- error: "command 'inlineBookmarks.refresh' not found"**
- restart vscode (-> the bookmarks for the file are now showing)
- open another file (-> no refresh of bookmarks - still showing for previous file)
**- [click on rescan workspace button]**

**Comment by tintinweb** [comment]
@mindfulJS

this might have been a side-effect of another bug. can you check out the latest version 0.0.10?
also for clarification: the refresh button reloads all known bookmark files and does not scan the whole workspace (we'd have to look into every file and I feel like there is no efficient way to do this yet).

**Comment by mindfulJS** [comment]
It all works perfectly now, thanks.
