### ISSUE TITLE
Command 'InlineBookmarks: List Bookmarks' resulted in an error (Running the contributed command: 'inlineBookmarks.listBookmarks' failed

### ISSUE THREAD

**Issue by carlitorendon** [tintinweb/vscode-inline-bookmarks#43]
First of all, thank you for a super useful extension. The concept is great. 

I did encounter the following error (as per the subject of this issue), when running the following command **InlineBookmarks: List Bookmarks**

![image](https://user-images.githubusercontent.com/14046845/131540986-33a67a35-0678-4af4-b328-c34ff8408d23.png)

I tried to look for logging in the output console but nothing seems to come out. I tried to see where I can increase the logging level but wasn't apparent to me (a bit of a newcomer to VS Code in General, coming from JetBrains). If I missed where can I increase the verbosity, kindly let me know. 

Here are the platform details: 
VS Code version: 1.59.1

tintinweb.vscode-inline-bookmarks version: 0.0.24

Again, thank you for the great work. 
RCL

**Comment by tintinweb** [comment]
Thank you for the report @carlitorendon. That's more than enough information to reproduce it. I'll get this out in the next couple of days.

cheers 🙌
tin
