### ISSUE TITLE
"inline-bookmarks.search.excludes" and "inline-bookmarks.search.includes" settings not working

### ISSUE THREAD

**Issue by kumardot93** [tintinweb/vscode-inline-bookmarks#44]

**Comment by tintinweb** [comment]
this is only being used in the `scanWorkspace` feature where the extension would try to find bookmarks in files in the current workspace. I guess that's not very clear from the description of the setting or is it not working correctly for you when scanning the workspace?

**Comment by kumardot93** [comment]
I have tried to avoid bookmarks from the env folder because it was taking too long to search. env folder contains python packages.
My settings.json file contains the following settings:
```

"inline-bookmarks.search.excludes": [
        "**/env/**",
        "**/frontend/node_modules/**",
    ],

```

I have checked many times,  it is now working or me.

**Comment by tintinweb** [comment]
Hey @kumardot93,

I cannot seem to reproduce. Files matching the pattern defined in `search.excludes` seem to be excluded from "workspace scanning". They will, however, show up if they're found in any editor and they will be added to the bookmarks view if a file containing a bookmark pattern is detected.

![image](https://user-images.githubusercontent.com/2865694/134744640-809311c2-8114-4391-b755-727be0572d53.png)
