### ISSUE TITLE
Simple proposal: please add `\\r` to the default regex settings (`"…[ \\t\\n$]"`)

### ISSUE THREAD

**Issue by schittli** [tintinweb/vscode-inline-bookmarks#46]
Hello

**thank you very much for sharing your great work!**

I have a simple suggestion: The default config uses this regex to match words: `"…[ \\t\\n$]"`
Depending on the File-Type (Linux, MacOS, Windows), this RegEx does not match. 

Therefore I propose to add `\r` to get: `"…[ \\t\\r\\n$]"`

Thanks a lot, kind regards,
Thomas

**Comment by tintinweb** [comment]
switching to `@audit\-info[\s]` should do the trick in almost all cases (except if the tag is right at the EOF).
