### ISSUE TITLE
Split View / Editor: inline-bookmark should just focus the Editor-Tab if the file is already opened

### ISSUE THREAD

**Issue by schittli** [tintinweb/vscode-inline-bookmarks#47]
Good evening

If VS Code has a split view / editor and we have this situation:

1. On the left side the file is open which contains an inline-bookmark
2. The current focused editor is on the right side 

```
+--Left Editor---------+--Right Editor--------+
| File1.xxx            |                      |
| Bookmarked           | Current focused      |
| File                 | Editor               |
|                      |                      |
|                      |                      |
+----------------------+----------------------+
```

If we now double-click a bookmark in the Inline Bookmarks List for `File1.xxx`, 
then inline-bookmark opens File1.xxx in the right editor.

If the target file is already open in an editor tab - no matter in which split-view editor - then it would be great if inline-bookmark just select this Editor tab.

Thanks a lot, kind regards,
Thomas

**Comment by tintinweb** [comment]
Hey @schittli, 

the "visible editors only" filter shows bookmarks for all visible editor windows. that's intentional. I am going to add an option that allows you to define whether "visible editors" is (1) all visible editors or (2) the currently active one if multiple are visible.
