### ISSUE TITLE
show nearest bookmark selected when moving cursor in file

### ISSUE THREAD

**Issue by mindfulJS** [tintinweb/vscode-inline-bookmarks#5]
It would be great to show the nearest (top) bookmark selected in the inline bookmarks panel when moving the cursor to a different line in the file (a la vscode's outline). That way we would know where we are in the file.

**Comment by tintinweb** [comment]
sounds like a good idea. I'll look at it next time I am working on a feature cycle 👍

**Comment by tintinweb** [comment]
Hey @mindfulJS, here's a first shot on this. still has some bugs though.

[vscode-inline-bookmarks-0 0 12 vsix (rename png->vsix)](https://user-images.githubusercontent.com/2865694/72186481-a9faa000-33f5-11ea-9d91-b7ad61f75f52.png)

Also goto vscode –> settings and enable **inline-bookmarks.view.follow** (True)

**Comment by mindfulJS** [comment]
Hey @tintinweb, that's good, well done. It seems though that it follows the scrolling rather than the cursor. It might be better (for usability, performance and accuracy) not to follow the mouse scrolling but rather to update the view when the user clicks somewhere else in the file.

**Comment by tintinweb** [comment]
makes sense -> fixed. there is one issue with the treeview api where it selects the wrong item if the bookmarks shares the same name. trying to figure out why it is acting this way because that's super annoying.
