### ISSUE TITLE
InlineBookmarks: Select Bookmark resulted in an error (filter is not a function)

### ISSUE THREAD

**Issue by alexn-s** [tintinweb/vscode-inline-bookmarks#50]
i just downloaded your extension and love it. however i encountered a bug when trying to run the command `InlineBookmarks: Select Bookmarks` which results in:

![image](https://user-images.githubusercontent.com/60710873/180593996-48a41d9a-098b-49d2-97c2-97bae59e38ab.png)

there are bookmarks available
![image](https://user-images.githubusercontent.com/60710873/180594039-47a7eaf8-0681-41e7-bed1-afb068a4df34.png)

and using command `InlineBookmarks: Select visible Bookmark` seems to work fine

![image](https://user-images.githubusercontent.com/60710873/180594078-02082364-d547-4876-ab6a-54436f1fa35a.png)

vscode info
```
Version: 1.69.2 (user setup)
Commit: 3b889b090b5ad5793f524b5d1d39fda662b96a2a
Date: 2022-07-18T16:12:52.460Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Windows_NT x64 10.0.22000
```

**Comment by tintinweb** [comment]
Hey @alexn-s 🙌

thanks for the feedback and for reporting this issue. Happy that you find the extension as useful as I do 😊. 
The command was missing a check for an optional filter function that got introduced with the `select visible bookmark` feature. Just published a fixed version.

cheers,

tin

PS: thanks for contributing as a sponsor to this project 🤗 much appreciated!
