### ISSUE TITLE
Not working with latest VSCode 1.72.0

### ISSUE THREAD

**Issue by mindfulJS** [tintinweb/vscode-inline-bookmarks#56]
I cannot see any inline bookmarks on the left panel anymore since upgrading to VsCode 1.72.0.
An error message appears: "Extension tintinweb.vscode-inline-bookmarks has provided an invalid tree item."

**Comment by eugenioclrc** [comment]
Same here

**Comment by momoca** [comment]
Same here

**Comment by tintinweb** [comment]
looking into it.

**Comment by tintinweb** [comment]
thanks @mindfulJS @eugenioclrc for reporting in. fixed with the [v0.1.0](https://github.com/tintinweb/vscode-inline-bookmarks/releases/tag/v0.1.0) I just published 🙌 

please let me know if you still run into problems. thanks!
