### ISSUE TITLE
highlight bookmark above instead of nearest (0.0.12)

### ISSUE THREAD

**Issue by mindfulJS** [tintinweb/vscode-inline-bookmarks#8]
Instead of highlighting the nearest please can you add the option to highlight the bookmark above? For example if bookmarks are used to define sections in the code, I would expect the bookmark above (title of the section) to be highlighted instead of the nearest.
I hope that makes sense.

**Comment by tintinweb** [comment]
what if the bookmark above is not in the visible range (but the next one is)? would that feel unnatural if it highlights the prevs instead of the one visible?

**Comment by mindfulJS** [comment]
good question - yes even if the bookmark above is not visible I would expect it to be highlighted as I need to know which section I am in. Obviously I use bookmarks to define sections so it currently feels unnatural to me in this particular case. Presumably other users may use the extension for other purposes so it might make sense to keep the two options I guess.

**Comment by tintinweb** [comment]
give it a try 😎 

## 0.0.13
- allow to specify bookmarks view follow behavior: `inline-bookmarks.view.followMode`
  - `nearest` - highlight the nearest bookmark (relative distance)
  - `chapter` - highlight the most recent bookmark, or the bookmark that is on the current line.

[vscode-inline-bookmarks-0 0 13 vsix (rename .png -> .vsix)](https://user-images.githubusercontent.com/2865694/72455556-4ab8d900-37c3-11ea-89d0-c49489b5bf4c.png)

**Comment by mindfulJS** [comment]
Hi @tintinweb, that's perfect.
Well done.
Ben
