### ISSUE TITLE
Can add a level to bookmarks make it look like a directory?

### ISSUE THREAD

**Issue by wangwangxingao** [tintinweb/vscode-inline-bookmarks#9]
Make it look like a directory
And does not show @xxx  
such as @todo "123"  only show  "123"

**Comment by tintinweb** [comment]
Hi @wangwangxingao 

> Make it look like a directory

can you elaborate on this?

> And does not show @xxx
> such as @todo "123" only show "123"

we can probably make this optional. would be good to get some input if others would also like to see this and if it should be the standard behavior. Atm it is shown as you can have multiple bookmark tags resolving to the same class and it might be useful to know the type.

**Comment by wangwangxingao** [comment]
such as use @lv1 @lv2 @lv3

@lv1 thisislv1
@lv2 thisislv2
@lv3 thisislv3
@lv3 thisislv3.2
@lv2 thisislv2.2

show：

@lv1 thisislv1
      ┗ @lv2 thisislv2
       │     ┗@lv3 thisislv3
       │     ┗@lv3 thisislv3.2
      ┗@lv2 thisislv2.2

**Comment by tintinweb** [comment]
added an option `inline-bookmarks.view.words.hide` to hide tags/trigger words in bookmarks view as per your request.

not sure about the levels though. what is the use-case for this? What if you get the levels wrong?

**Comment by tintinweb** [comment]
let's closed for now and re-open if there are more requests for this.
